name: Build MelonLoader

run-name: 0.7.2${{ github.event_name != 'workflow_dispatch' && format('-ci.{0}', github.run_number) || '' }} | ${{ github.event_name != 'workflow_dispatch' && (github.event.head_commit.message || format('`[PR]` {0}', github.event.pull_request.title)) || 'Manual Build' }}

on:
  push:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  pull_request:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/compile_all.yml
    with:
      SKIP_DEBUG: false
      VERSION: "0.7.2${{ github.event_name != 'workflow_dispatch' && format('.{0}', github.run_number) || '' }}"